project:
  type: book
  output-dir: docs

book:
  title: "Ecología Microbiana y Herramientas bioinformáticas"
  author: 
    name: "[BCEM](https://bcem-uniandes.github.io/people.html)"
    affiliation: "[Universidad de los Andes](https://uniandes.edu.co)"
  sidebar:
    style: floating
  date-format: "YYYY-MM-DD"
  date: "2024-01-01"
  chapters:
    - index.qmd
    - chapters/01-cli-dbs.qmd
    # - chapters/02-read-processing.qmd
    # - chapters/03-qiime.qmd
    # - chapters/04-diversity-analisis.qmd
    # - chapters/05-taxa-assignment.qmd
    # - chapters/06-microviz-analyses.qmd
    # - chapters/07-mag-assembly.qmd
    # - chapters/08-binning.qmd
    # - chapters/09-comparative-genomics.qmd
    - references.qmd

bibliography: references.bib

fig-align: center
df-print: paged
code-link: true
code-annotations: select
freeze: auto
execute:
  cache: true
lang: es

format:
  html:
    theme: cosmo
    code-link: true
    code-copy: hover
    df-print: paged
    fig-align: center
    highlight-style: ayu
    embed-resources: true



